language: node_js

node_js:
  - 4.1.1

before_install:
  - npm install -g bower
  - npm install gulpjs/gulp-cli -g

before_script:
  - npm install
  - cd test/examples && bower install

script:
  - gulp
  - gulp js
  - gulp css
  - gulp html
