language: node_js

node_js:
  - 4.1.1

before_install:
  - npm install -g bower
  - npm install -g gulp

before_script:
  - npm install
  - cd test/examples && bower install

script:
  - gulp --silent
  - gulp js:build --silent
  - gulp css:build --silent
  - gulp twig:build --silent
