language: node_js

node_js:
  - 4.1.1

before_install:
  - npm install -g bower
  - npm install -g gulp

before_script:
  - npm install
  - cd examples && bower install

script:
  - ./node_modules/.bin/gulp --silent
  - ./node_modules/.bin/gulp js:build --silent
  - ./node_modules/.bin/gulp css:build --silent
  - ./node_modules/.bin/gulp twig:build --silent
