language: node_js

node_js:
  - 4.1.1

before_install:
  - npm install -g bower
  - npm install gulpjs/gulp-cli -g

before_script:
  - npm install
  - cd test/examples && bower install

script:
  - gulp --gulpfile gulpfile.dustman.js
  - gulp js --gulpfile gulpfile.dustman.js
  - gulp css --gulpfile gulpfile.dustman.js
  - gulp html --gulpfile gulpfile.dustman.js
